### ISSUE TITLE
Is pose inference slow compared to native or is it the flutter canvas?

### ISSUE THREAD

**Issue by danj96dev** [bharat-biradar/Google-Ml-Kit-plugin#107]
When I compare the pose tracking side by side, native android seems to be faster and smoother.
The smoothness is probably from smoothing out the coordinates but the tracking feels like it lags behind on the flutter library. Is this because stream mode hasn't been updated or because the canvas draws on the next frame in flutter, making it seem like it's behind the person in the camera feed?

**Comment by fbernaly** [comment]
Yes, I have noticed some lagging as well. I think it is due to the FlutterMethodChannels, there is a small delay passing all that camera feed from Flutter to the native methods. We will look if there is a way to improve that, you are welcome to send a PR if you are interested in getting this fixed.

For now, closing this one for inactivity.
