### ISSUE TITLE
[iOS] Cannot compile: FirebaseApp.configure() missing

### ISSUE THREAD

**Issue by S-Man42** [bharat-biradar/Google-Ml-Kit-plugin#143]
I following your `README `instructions to compile the app for iOS.

Unfortunately, I couldn't compile it with your sole instructions (FirebaseApp not configured).

I found a way to solve the problem. Just add

`FirebaseApp.configure()`

to AppDelegate.swift file.

When I tried to execute the barcode function, the iOS app crashed.

I needed to

1. register an app on firebase.google.com
2. Download the `GoogleService-Info.plist `
3. Add it to my app code

However. I am not quite sure if

1. Is there a way get the app run without the plist file?
2. The app is not thought to get internet access. Can the google_ml_kit lib used completely offline. I am not quite sure why it needs a Firebase account. Is only required while compiling or does the app need internet access now?

**Comment by marinkobabic** [comment]
I'm having the same issue. Any feedback. With version 0.6.0 all worked fine.

**Comment by marinkobabic** [comment]
It looks like you have introduced MLKitLinkFirebase. But by using this kit the idea was to not rely on firebase and to use the library completely offline. Is there an option to disable the usage of Firebase so that we are not getting the error
```
The default Firebase app has not yet been configured. Add `FirebaseApp.configure()
```
with the version 0.7.2 compilation works fine, but when it comes to the starting the stream the message above is reported and the app crashes.

**Comment by KexiHe** [comment]
I am having the same problem. May be the reason is that: this plugin depends on Firebase in this version 0.7.2.  This is the evidences. By the way, I don't have a good idea to solve it, may be I have to avoiding this plugin or use/create another.

1. Plugin podspec
[https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/ios/google_ml_kit.podspec](url)
->Line 22, 23
[  s.dependency 'GoogleMLKit/ImageLabelingCustom', '~> 2.2.0'
  s.dependency 'GoogleMLKit/LinkFirebase', '~> 2.2.0' ]

2. About MLKit
[https://developers.google.com/ml-kit/vision/image-labeling/custom-models/ios?hl=en](url)
 ->[Hosted Model] ->[Requires a Firebase project]

3.The example using this plugin including process initializing Firebase
[https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/example/ios/Runner/AppDelegate.m](url)

**Comment by fbernaly** [comment]
Image Labeling and Object tracking can have remote custom models downloaded from Firebase, in order to wrap all that functionality under the same plugin both [google_mlkit_image_labeling](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_image_labeling) and [google_mlkit_object_detection](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_object_detection) depend on Firebase. If you are using any of the others API then you do not need include Firebase.

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_image_labeling#firebase-dependency
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_object_detection#firebase-dependency



We have updated the readme for our example app in the last version: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit/example#getting-started
