### ISSUE TITLE
App won't build for Web

### ISSUE THREAD

**Issue by millerovv** [bharat-biradar/Google-Ml-Kit-plugin#245]
Hi! We've been actively using `google_ml_kit` for text recognition. 
Not so long ago we switched to [our own fork](https://github.com/simpleclub-extended/Google-Ml-Kit-plugin) of the library in order to minimize APK sizes by removing unnecessary ML packages. 

@fbernaly [contacted us](https://github.com/simpleclub-extended/Google-Ml-Kit-plugin/pull/1#issuecomment-1105486674) with a proposal to try out the new version of the `google_ml_kit` that introduced packages split. 

Our app runs on mobile and web platforms, and we've encountered a problem, that after depending on 
`google_mlkit_text_recognition 0.3.0` the builds start failing. Here's the type of errors we see in the logs:

![image](https://user-images.githubusercontent.com/31796433/166473348-0d61d4d8-e885-430b-9f8c-d30b76b986f8.png)

Strangely, there weren't any issues with running our app on Web while depending on `google_ml_kit` or our fork.
Is there any way, `google_mlkit_text_recognition` could also be updated in order to support web builds? 
Thanks!

**Comment by fbernaly** [comment]
@millerovv : are you running google_ml_kit on web? We did not include web target, actually ML Kit is only for iOS and Android as per Google's website: https://developers.google.com/ml-kit

If you are doing, could you provide more details, I am interested to know how.

**Comment by millerovv** [comment]
@fbernaly 👋  
We only use google_ml_kit functionality on mobile platforms. On the Web version of the app the features that require ML are not available to the user. Therefore, it's inconvenient that `google_mlkit_text_recognition` prevents us from building single project for all of the platforms.

**Comment by fbernaly** [comment]
Ok, will try that in a demo project and let you know.

**Comment by vmalyi** [comment]
@fbernaly, any help needed here to move this forward?

**Comment by fbernaly** [comment]
@vmalyi, @millerovv:

I created a Flutter project with `image_picker` and `google_mlkit_text_recognition`, for both iOS, Android and web. Simple app: button in the center of the screen, it opens the image picker, once image is selected then an `InputImage` is created from path, then passed to `TextRecognizer`, `recognizedText` is printed in the console.

And so far, it is working for the 3 platforms, of course for web it is not recognizing any text because the channel method is not implemented for that platform, but other that getting the expect platform error, it is working... no crash or building errors.

I think is it something else related to your project or the other dependencies you have in your project. So far our plugin is working as expected, and I dont know how else to help you.

BTW, the logs you are sharing in your screenshoot it is complaining for files in dartlang source code, not of those are use in this plugin.

Here you have a link to my POC: https://github.com/fbernaly/web_text_recognition_poc

I hope that helps.

**Comment by fbernaly** [comment]
@millerovv  and @vmalyi : any update? did you try my POC?

**Comment by millerovv** [comment]
Hi @fbernaly!
Sorry for the delayed response. Thank you for that example! It turns out, that the package had conflicts with some other dependencies in our project. We managed to overcome that problem and the app successfully launched on web. 
Appreciate your help on this. Let's resolve that issue 👍

**Comment by fbernaly** [comment]
Great I am glad it is fixed

**Comment by jtkeyva** [comment]
@fbernaly do you know if there is any chance of this being supported for web? would be nice to have handwriting recognition for web. thx

**Comment by fbernaly** [comment]
@jtkeyva : MLKit it is only for mobile: https://developers.google.com/ml-kit
Our plugin it is just a wrapper on top of what Google develops. If they release a web version then we will include it, but that will be an ask for them.
