### ISSUE TITLE
Save Digital Ink as SVG?

### ISSUE THREAD

**Issue by jtkeyva** [bharat-biradar/Google-Ml-Kit-plugin#260]
Is it possible to save the digital ink as an svg file?
thanks

**Comment by fbernaly** [comment]
Thanks for using this plugin!!!

This plugin will help you to recognize text from a given [Ink](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_digital_ink_recognition/lib/src/digital_ink_recognizer.dart#L90-L99), which is a collection of [Stroke](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_digital_ink_recognition/lib/src/digital_ink_recognizer.dart#L102-L110), which includes all the [StrokePoint](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_digital_ink_recognition/lib/src/digital_ink_recognizer.dart#L113-L132).

Once you capture the `Ink`, you need to pass it to the [DigitalInkRecognizer](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_digital_ink_recognition/lib/src/digital_ink_recognizer.dart#L10-L49), which will return the `RecognitionCandidate`. In the example app we demonstrate how you can capture the `Ink` using a `GestureDetector` on a `CustomPaint` widget.

Technically you could save the `Ink` as an svg file because `Ink` is basically a collection of points. However, that is outside the scope of this plugin.

Here you have some resources you can use to achieve your goal:
- https://pub.dev/packages/flutter_svg
- https://www.youtube.com/watch?v=DSJ5vONP3XM
- https://medium.com/flutter-community/export-your-widget-to-image-with-flutter-dc7ecfa6bafb
- https://mukhtharcm.com/create-image-from-widget-flutter/
- https://www.codegrepper.com/code-examples/dart/flutter+save+canvas+as+svg
- https://www.codegrepper.com/code-examples/dart/flutter+export+canvas+as+svg

**Comment by jtkeyva** [comment]
aweseome! thanks for the thorough answer. i'll poke around. some drawing packages have brush thickness and fancy brushes, perhaps ill try to implement that at some point
