### ISSUE TITLE
File Not Found (Persmission Denied)

### ISSUE THREAD

**Issue by luffynas** [bharat-biradar/Google-Ml-Kit-plugin#262]
I was try **google_mlkit_face_detection** v.0.3.0 and return error after take photo from camera like this:

```
W/System.err(13795): 	at libcore.io.IoBridge.open(IoBridge.java:478)
W/System.err(13795): 	... 20 more
W/OpenGLRenderer(13795): EGL Surface is invalid, Drawing was requested on a context with no surface! draw()
I/Counters(13795): exceeded sample count in FrameTime
W/OpenGLRenderer(13795): EGL Surface is invalid, Drawing was requested on a context with no surface! draw()
E/flutter (13795): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(InputImageConverterError, java.io.FileNotFoundException: /: open failed: EACCES (Permission denied), null, null)
```

How to solve this issue?

**Android Manifest**
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
```

**Legacy Code**
`android:requestLegacyExternalStorage="true"`

**Flutter Version**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by fbernaly** [comment]
@luffynas: that seems more like an issue with how you are capturing the image rather than the plugin, how are you capturing the image. This plugin does not capture the image, once you have capture the image: from the gallery or the camera, this plugin only detects the faces in the give `InputImage`. We do not requiere you to add and permission to your manifest or  setting any legacy flag like you shared above. That is why I think this is most an issue with how you capturing the image. Once you capture your `CameraImage` or you have the path from the gallery, you need to create an `InputImage`: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_commons/lib/src/input_image.dart

Did you try our example app? https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit/example
