### ISSUE TITLE
Which size should be the input image inorder to detects all its objects 

### ISSUE THREAD

**Issue by hassanyassiin** [bharat-biradar/Google-Ml-Kit-plugin#273]
First I tried to inset this image, it detects null 

![image_one](https://user-images.githubusercontent.com/94860683/171431700-2115284f-874a-4be4-a760-586bb9137a16.jpeg)

Then when I cropped it, it detects 3 objects, great!!
![image_two](https://user-images.githubusercontent.com/94860683/171431899-ae62176d-9c31-4854-9041-984b74842177.jpeg)

Also this image it detects objects without cropping (one object).

![image_three](https://user-images.githubusercontent.com/94860683/171431955-ceeb7c3f-e76c-486b-99e3-ee1c6a159af4.jpeg)

But while I cropped it it detects 0 objects 

![Image_four](https://user-images.githubusercontent.com/94860683/171432024-bae50eed-6993-4f34-8aa0-7af87217e736.jpeg)

So what should I do with this issue ?

**Comment by fbernaly** [comment]
There are 3 constructor methods for an `InputImage`:
- from file path
- from file
- from bytes

Only when you create an `InputImage` from bytes you need to set the size.  And from what you have share it seems that you are using the path, so, you do not need to set the size. I guess your issue is another: you are not setting the correct settings for the object detector:

Since you are processing only one image you need to set the detector options in single mode:

```
final options = ObjectDetectorOptions(mode: DetectionMode.single, classifyObjects: true, multipleObjects: true);
```

**Comment by fbernaly** [comment]
Interesting... I uploaded your images and tested with our example app and I am getting the same result, when the image is cropped it is not detecting the object, but so far I think it is the Google API not detecting. What I would recommend you to do is: try Google's sample app and try your images, if you still can reproduce the issue, then we need to report the issue to Google. 

You can get their example app here: https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision
