### ISSUE TITLE
How do I run face detector in an isolate ?

### ISSUE THREAD

**Issue by radha1990kumari** [bharat-biradar/Google-Ml-Kit-plugin#86]
My code sample :-
```dart
static void entryPoint(SendPort sendPort) async {
    final port = ReceivePort();
    sendPort.send(port.sendPort);

    await for (final IsolateData isolateData in port) {
      if (isolateData != null) {
        final InputImage inputImage =
            InputImage.fromFilePath(isolateData.imagePath);
        final FaceDetector faceDetector = GoogleMlKit.vision
            .faceDetector(FaceDetectorOptions(mode: FaceDetectorMode.accurate));

        final List<Face> outputFaces =
            await faceDetector.processImage(inputImage);
```
I am getting this  error :-
```
[ERROR:flutter/runtime/dart_isolate.cc(1137)] Unhandled exception:
E/flutter (19496): Null check operator used on a null value
E/flutter (19496): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter (19496): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter (19496): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter (19496): #3      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344:41)
E/flutter (19496): #4      FaceDetector.processImage (package:google_ml_kit/src/vision/face_detector.dart:54:41)
E/flutter (19496): #5      IsolateUtils.entryPoint (package:facel/isolates.dart:80:32)
```

**Comment by radha1990kumari** [comment]
I am closing this cause I just ran it on main isolate and passed the data to another isolate

**Comment by bharat-biradar** [comment]
@radha1990kumari Please share your code snippet here so it might be helpful to others who might come across this issue.

**Comment by radha1990kumari** [comment]
@bharat-biradar  , I am not running the face detection in a separate  spawned isolate (since I was not able to find a way to do it ). So, the `Readme`  of the package would suffice.  For those wanting to do so ,I don't  think there  is any need to, cause running the Face detector in main isolate didn't hang up my UI (which was my main concern ) but after getting the list of `Face` objects further processing (cropping detected faces and running them through a` tflite` model ) did . 
So, what I did is I created an `interpreter` instance in main isolate and bundled the `interpreter` address and `List<Face>` in an `isolateData` object
```dart
class IsolateData {
  int interpreterAddress;
  List<Face> faces;
  Uint8List image;
  SendPort responsePort;
  IsolateData(
      {this.interpreterAddress,
      this.image,
      this.faces});
}
```

**Comment by om-ha** [comment]
I think this is a good issue to explore further. For example let's talk about TextRecognition. You have:
1. Camera View: Many FPS with high resolution according to resolution preset e.g. `ResolutionPreset.medium`.
2. Text Recognition by MLKit
3. Annotations above CameraView
4. Your in-house processing of recognized text
 
 Having all of this run on main isolate sounds scary. This issue is the [only mention](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/search?q=isolate&type=) of `isolate` within this repo.
 
 I wish this would be discussed further.
 
 For example, for points **2.** & **4.** above

>  2. Text Recognition by MLKit platform 
>  4. Your in-house processing of recognized text

It could be argued that these can happen on different isolates. 
In fact 2. is [occurring in platform-plugin land](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/ios/Classes/vision/TextRecognizer.m) (native) So that's probably its own isolate.

But what about **1.** & **3.**? 
For **1.** it's actually [Camera](https://pub.dev/packages/camera) pub package, which is actually a platform plugin too. 
For 3., I think it's okay to create/destruct UI widgets a lot? which is what flutter is good at with its generational garbage collector.
