### ISSUE TITLE
Creating InputImage from Bytes doesn't work

### ISSUE THREAD

**Issue by jtmuller5** [bharat-biradar/Google-Ml-Kit-plugin#9]
The Pose Detector only seems to work when you create your InputImage from a file path (InputImage.fromFilePath). When I attempt to create the InputImage using the fromBytes() constructor the output is always blank. I've tried all sorts of different configurations, including changing the image rotation and format, but the result is always blank.

Have you had success with this?

**Comment by bharat-biradar** [comment]
Hi, @jtmuller5 thanks for opening an issue. This problem is not only with pose detector but with other api's too, I updated this in the readme but have not published this again on pub.dev so you might not have seen it. I too tried all possibilities with other api's as well but could get results, if I find a breakthrough I will surely update you.

**Comment by fbernaly** [comment]
@jtmuller5: here is how you create an InputImage from Bytes:

```
    CameraImage image;
    final WriteBuffer allBytes = WriteBuffer();
    for (Plane plane in image.planes) {
      allBytes.putUint8List(plane.bytes);
    }
    final bytes = allBytes.done().buffer.asUint8List();
    final Size imageSize = Size(image.width.toDouble(), image.height.toDouble());
    final inputImageData = InputImageData(
      size: imageSize,
    );
    final inputImage = InputImage.fromBytes(bytes: bytes, inputImageData: inputImageData);
```

We are using that here: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/example/lib/VisionDetectorViews/camera_view.dart#L216-L228
 and it is working.

**Comment by augustinharter** [comment]
I have the same problem and it seems like this issue was not resolved properly?

the answer from @fbernaly seems outdated since creating InputImageDate from imageSize only is not supported with the current version as far as I can tell. Also his link to the source code base seems outdated and wrong.

`void processImage(XFile file) {
    // READ File Bytes
    File(file.path).readAsBytes().then((bytes) {
      // decode image to get imageSize
      decodeImageFromList(bytes).then((img) {
        setState(() {
          imageSize = Size(img.width.toDouble(), img.height.toDouble());
          currentImage = Image.memory(bytes);
          _showLive = false;
        });

        
        // Not Working: fromBytes
        var inputImage = InputImage.fromBytes(
              bytes: bytes,
              inputImageData: InputImageData(
                  size: imageSize,
                  imageRotation: InputImageRotation.Rotation_0deg,
                  inputImageFormat: InputImageFormat.NV21,
                  planeData: null),
            );
        // Working:
        //var inputImage = InputImage.fromFilePath(file.path);

        // DETECT OBJECTS
        objectDetector.processImage(inputImage).then((recognitions) {
          //mostly empty, sometimes some big and wrong boxes are detected
          print("MY recognitions $recognitions");
       ....
          `

I tried all InputImageFormats and all InputImageRotations, but nothing seems to work.

Any idea?

**Comment by realArafatBen** [comment]
Currently, I am stuck here... how can I get the inputImageData from a file. 
All that is been returned is null
